version: "2.4"

services:
  octoprint:
    image: octoprint/octoprint
    container_name: octoprint
    environment:
      - ENABLE_MJPG_STREAMER=true
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/video0:/dev/video0
    volumes:
      - data:/octoprint
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.octoprint.entrypoints=websecure

networks:
  default:
    name: proxy
    external: true

volumes:
  data:
