version: "2.4"

services:
  octoprint:
    image: octoprint/octoprint
    container_name: octoprint
    environment:
      - ENABLE_MJPG_STREAMER=true
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/video0:/dev/video0
    volumes:
      - octoprint_data:/octoprint
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.octoprint.rule=Host(`octoprint.tobyvin.com`)
      - traefik.http.routers.octoprint.middlewares=auth
      - traefik.http.services.octoprint.loadbalancer.server.port=80

networks:
  default:
    name: proxy
    external: true

volumes:
  octoprint_data:
    external: true
      
